### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [buzzfeed-openlab/shit-vcs-say#32]
about this code: https://github.com/buzzfeed-openlab/shit-vcs-say/blob/40d8c07702ad315c4533815aadf2be5234da15e1/server/models/create-prod.js#L394

see [Tasks versus root/direct queries](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries) ;)

**Comment by WestleyArgentum** [comment]
heh, thanks for pointing that out... I'm really embarrassed by all of this code >.<

**Comment by vitaly-t** [comment]
No worries :)

And if you have to do it in a high-performance app, this read is useful: [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost) ;)
